# ===== APPLICATION =====
spring.application.name=SmartInvoicePro
server.port=8080

# ===== SQL SERVER DATASOURCE =====
#spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:sqlserver://localhost:1433;databaseName=smartInvoicePro;encrypt=true;trustServerCertificate=true}
#spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sa}
#spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:mohamed1234}
#spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver


# ===== POSTGRESQL DATASOURCE =====
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/smartinvoicepro}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===== JPA / HIBERNATE =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===== JWT =====
app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
app.jwt.expiration-ms=86400000

# ===== SPRINGDOC / SWAGGER =====
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# ===== LOGGING =====
logging.level.com.smartInvoicePro=DEBUG
logging.level.org.springframework.security=DEBUG
